-dontwarn me.pushy.**
-keep class me.pushy.** { *; }
-keep class androidx.core.app.** { *; }
-keep class android.support.v4.app.** { *; }
-keep class io.flutter.** { *; }
-keep class io.flutter.plugins.** { *; }
